/*
 * This file is generated by jOOQ.
*/
package com.travelneer.jooq.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRoles implements Serializable {

    private static final long serialVersionUID = -999969238;

    private Integer userId;
    private Byte    roleId;

    public UserRoles() {}

    public UserRoles(UserRoles value) {
        this.userId = value.userId;
        this.roleId = value.roleId;
    }

    public UserRoles(
        Integer userId,
        Byte    roleId
    ) {
        this.userId = userId;
        this.roleId = roleId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Byte getRoleId() {
        return this.roleId;
    }

    public void setRoleId(Byte roleId) {
        this.roleId = roleId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserRoles (");

        sb.append(userId);
        sb.append(", ").append(roleId);

        sb.append(")");
        return sb.toString();
    }
}
