version: '3'
services:

  nginx:
    container_name: travelneer-nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443   
    networks:
      - external_network 
    depends_on:
      - travelneer
    links:
      - travelneer:travelneer 
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d  

  travelneer:    
    image: travelneer/spring-boot-main:0.0.1-SNAPSHOT
    restart: always    
    networks:
      - external_network
      - internal_network
    links:
      - db:mysql-container 
    ports:
      - 8080:8080    
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb:latest 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'whatever'
      MYSQL_DATABASE: 'travelneer'
      MYSQL_USER: 'travelneer'
      MYSQL_PASS: '12345678'
    networks:      
      - internal_network  
    volumes: 
      - ./mariadb/data:/var/lib/mariadb
      - ./mariadb/dump:/docker-entrypoint-initdb.d/

networks:
  external_network:
  internal_network:
    internal: true        