version: '3'
services:

  nginx:
   container_name: travelneer-nginx
   image: nginx:1.13
   restart: always
   ports:
   - 80:80
   - 443:443
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   depends_on:
   - travelneer

  # MySQL Service
  db:
    container_name: db
    restart: always
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'ur!prepared'
      MYSQL_USER: 'travelneer'
      MYSQL_PASS: '12345678'
    ports:
      - "3306:3306"

  travelneer:
    container_name: travelneer-spring-boot
    restart: always    
    build: ./server/travelneer-spring-boot
    working_dir: /server/travelneer-spring-boot
    volumes:
      - ./server/travelneer-spring-boot/tmp:/server-travelneer-spring-boot
