ALTER TABLE country
ADD COLUMN profile_image_url VARCHAR(100) AFTER name;


UPDATE country SET profile_image_url = '/countries-profiles/afghanistan' WHERE name = 'Afghanistan';
UPDATE country SET profile_image_url = '/countries-profiles/albania' WHERE name = 'Albania';
UPDATE country SET profile_image_url = '/countries-profiles/algeria' WHERE name = 'Algeria';
UPDATE country SET profile_image_url = '/countries-profiles/american-samoa' WHERE name = 'American Samoa';
UPDATE country SET profile_image_url = '/countries-profiles/andorra' WHERE name = 'Andorra';
UPDATE country SET profile_image_url = '/countries-profiles/angola' WHERE name = 'Angola';
UPDATE country SET profile_image_url = '/countries-profiles/anguilla' WHERE name = 'Anguilla';
UPDATE country SET profile_image_url = '/countries-profiles/antigua-and-barbuda' WHERE name = 'Antigua and Barbuda';
UPDATE country SET profile_image_url = '/countries-profiles/argentina' WHERE name = 'Argentina';
UPDATE country SET profile_image_url = '/countries-profiles/armenia' WHERE name = 'Armenia';
UPDATE country SET profile_image_url = '/countries-profiles/aruba' WHERE name = 'Aruba';
UPDATE country SET profile_image_url = '/countries-profiles/australia' WHERE name = 'Australia';
UPDATE country SET profile_image_url = '/countries-profiles/austria' WHERE name = 'Austria';
UPDATE country SET profile_image_url = '/countries-profiles/azerbaijan' WHERE name = 'Azerbaijan';
UPDATE country SET profile_image_url = '/countries-profiles/bahamas' WHERE name = 'Bahamas';
UPDATE country SET profile_image_url = '/countries-profiles/bahrain' WHERE name = 'Bahrain';
UPDATE country SET profile_image_url = '/countries-profiles/bangladesh' WHERE name = 'Bangladesh';
UPDATE country SET profile_image_url = '/countries-profiles/barbados' WHERE name = 'Barbados';
UPDATE country SET profile_image_url = '/countries-profiles/belarus' WHERE name = 'Belarus';
UPDATE country SET profile_image_url = '/countries-profiles/belgium' WHERE name = 'Belgium';
UPDATE country SET profile_image_url = '/countries-profiles/belize' WHERE name = 'Belize';
UPDATE country SET profile_image_url = '/countries-profiles/benin' WHERE name = 'Benin';
UPDATE country SET profile_image_url = '/countries-profiles/bermuda' WHERE name = 'Bermuda';
UPDATE country SET profile_image_url = '/countries-profiles/bhutan' WHERE name = 'Bhutan';
UPDATE country SET profile_image_url = '/countries-profiles/bolivia' WHERE name = 'Bolivia';
UPDATE country SET profile_image_url = '/countries-profiles/bosnia-and-herzegovina' WHERE name = 'Bosnia and Herzegovina';
UPDATE country SET profile_image_url = '/countries-profiles/botswana' WHERE name = 'Botswana';
UPDATE country SET profile_image_url = '/countries-profiles/brazil' WHERE name = 'Brazil';
UPDATE country SET profile_image_url = '/countries-profiles/british-indian-ocean-territory' WHERE name = 'British Indian Ocean Territory';
UPDATE country SET profile_image_url = '/countries-profiles/brunei' WHERE name = 'Brunei';
UPDATE country SET profile_image_url = '/countries-profiles/bulgaria' WHERE name = 'Bulgaria';
UPDATE country SET profile_image_url = '/countries-profiles/burkina-faso' WHERE name = 'Burkina Faso';
UPDATE country SET profile_image_url = '/countries-profiles/burundi' WHERE name = 'Burundi';
UPDATE country SET profile_image_url = '/countries-profiles/cambodia' WHERE name = 'Cambodia';
UPDATE country SET profile_image_url = '/countries-profiles/cameroon' WHERE name = 'Cameroon';
UPDATE country SET profile_image_url = '/countries-profiles/canada' WHERE name = 'Canada';
UPDATE country SET profile_image_url = '/countries-profiles/cape-verde' WHERE name = 'Cape Verde';
UPDATE country SET profile_image_url = '/countries-profiles/cayman-islands' WHERE name = 'Cayman Islands';
UPDATE country SET profile_image_url = '/countries-profiles/central-african-republic' WHERE name = 'Central African Republic';
UPDATE country SET profile_image_url = '/countries-profiles/chad' WHERE name = 'Chad';
UPDATE country SET profile_image_url = '/countries-profiles/chile' WHERE name = 'Chile';
UPDATE country SET profile_image_url = '/countries-profiles/china' WHERE name = 'China';
UPDATE country SET profile_image_url = '/countries-profiles/christmas-island' WHERE name = 'Christmas Island';
UPDATE country SET profile_image_url = '/countries-profiles/cocos-island' WHERE name = 'Cocos Island';
UPDATE country SET profile_image_url = '/countries-profiles/colombia' WHERE name = 'Colombia';
UPDATE country SET profile_image_url = '/countries-profiles/comoros' WHERE name = 'Comoros';
UPDATE country SET profile_image_url = '/countries-profiles/democratic-republic-of-congo' WHERE name = 'Democratic Republic of Congo';
UPDATE country SET profile_image_url = '/countries-profiles/republic-of-the-congo' WHERE name = 'Republic of The Congo';
UPDATE country SET profile_image_url = '/countries-profiles/cook-islands' WHERE name = 'Cook Islands';
UPDATE country SET profile_image_url = '/countries-profiles/costa-rica' WHERE name = 'Costa Rica';
UPDATE country SET profile_image_url = '/countries-profiles/croatia' WHERE name = 'Croatia';
UPDATE country SET profile_image_url = '/countries-profiles/cuba' WHERE name = 'Cuba';
UPDATE country SET profile_image_url = '/countries-profiles/cyprus' WHERE name = 'Cyprus';
UPDATE country SET profile_image_url = '/countries-profiles/czech-republic' WHERE name = 'Czech Republic';
UPDATE country SET profile_image_url = '/countries-profiles/denmark' WHERE name = 'Denmark';
UPDATE country SET profile_image_url = '/countries-profiles/djibouti' WHERE name = 'Djibouti';
UPDATE country SET profile_image_url = '/countries-profiles/dominica' WHERE name = 'Dominica';
UPDATE country SET profile_image_url = '/countries-profiles/dominican-republic' WHERE name = 'Dominican Republic';
UPDATE country SET profile_image_url = '/countries-profiles/east-timor' WHERE name = 'East Timor';
UPDATE country SET profile_image_url = '/countries-profiles/ecuador' WHERE name = 'Ecuador';
UPDATE country SET profile_image_url = '/countries-profiles/egypt' WHERE name = 'Egypt';
UPDATE country SET profile_image_url = '/countries-profiles/salvador' WHERE name = 'Salvador';
UPDATE country SET profile_image_url = '/countries-profiles/equatorial-guinea' WHERE name = 'Equatorial Guinea';
UPDATE country SET profile_image_url = '/countries-profiles/eritrea' WHERE name = 'Eritrea';
UPDATE country SET profile_image_url = '/countries-profiles/estonia' WHERE name = 'Estonia';
UPDATE country SET profile_image_url = '/countries-profiles/ethiopia' WHERE name = 'Ethiopia';
UPDATE country SET profile_image_url = '/countries-profiles/falkland-islands' WHERE name = 'Falkland Islands';
UPDATE country SET profile_image_url = '/countries-profiles/faroe-islands' WHERE name = 'Faroe Islands';
UPDATE country SET profile_image_url = '/countries-profiles/fiji' WHERE name = 'Fiji';
UPDATE country SET profile_image_url = '/countries-profiles/finland' WHERE name = 'Finland';
UPDATE country SET profile_image_url = '/countries-profiles/france' WHERE name = 'France';
UPDATE country SET profile_image_url = '/countries-profiles/guyana' WHERE name = 'Guyana';
UPDATE country SET profile_image_url = '/countries-profiles/french-polynesia' WHERE name = 'French Polynesia';
UPDATE country SET profile_image_url = '/countries-profiles/gabon' WHERE name = 'Gabon';
UPDATE country SET profile_image_url = '/countries-profiles/gambia' WHERE name = 'Gambia';
UPDATE country SET profile_image_url = '/countries-profiles/georgia' WHERE name = 'Georgia';
UPDATE country SET profile_image_url = '/countries-profiles/germany' WHERE name = 'Germany';
UPDATE country SET profile_image_url = '/countries-profiles/ghana' WHERE name = 'Ghana';
UPDATE country SET profile_image_url = '/countries-profiles/gibraltar' WHERE name = 'Gibraltar';
UPDATE country SET profile_image_url = '/countries-profiles/guernsey' WHERE name = 'Guernsey';
UPDATE country SET profile_image_url = '/countries-profiles/greece' WHERE name = 'Greece';
UPDATE country SET profile_image_url = '/countries-profiles/greenland' WHERE name = 'Greenland';
UPDATE country SET profile_image_url = '/countries-profiles/grenada' WHERE name = 'Grenada';
UPDATE country SET profile_image_url = '/countries-profiles/guam' WHERE name = 'Guam';
UPDATE country SET profile_image_url = '/countries-profiles/guatemala' WHERE name = 'Guatemala';
UPDATE country SET profile_image_url = '/countries-profiles/guinea' WHERE name = 'Guinea';
UPDATE country SET profile_image_url = '/countries-profiles/guinea-bissau' WHERE name = 'Guinea-Bissau';
UPDATE country SET profile_image_url = '/countries-profiles/guyana' WHERE name = 'Guyana';
UPDATE country SET profile_image_url = '/countries-profiles/haiti' WHERE name = 'Haiti';
UPDATE country SET profile_image_url = '/countries-profiles/honduras' WHERE name = 'Honduras';
UPDATE country SET profile_image_url = '/countries-profiles/hong-kong' WHERE name = 'Hong Kong';
UPDATE country SET profile_image_url = '/countries-profiles/hungary' WHERE name = 'Hungary';
UPDATE country SET profile_image_url = '/countries-profiles/iceland' WHERE name = 'Iceland';
UPDATE country SET profile_image_url = '/countries-profiles/india' WHERE name = 'India';
UPDATE country SET profile_image_url = '/countries-profiles/isle-of-man' WHERE name = 'Isle of Man';
UPDATE country SET profile_image_url = '/countries-profiles/indonesia' WHERE name = 'Indonesia';
UPDATE country SET profile_image_url = '/countries-profiles/iran' WHERE name = 'Iran';
UPDATE country SET profile_image_url = '/countries-profiles/iraq' WHERE name = 'Iraq';
UPDATE country SET profile_image_url = '/countries-profiles/ireland' WHERE name = 'Ireland';
UPDATE country SET profile_image_url = '/countries-profiles/israel' WHERE name = 'Israel';
UPDATE country SET profile_image_url = '/countries-profiles/italy' WHERE name = 'Italy';
UPDATE country SET profile_image_url = '/countries-profiles/ivory-coast' WHERE name = 'Ivory Coast';
UPDATE country SET profile_image_url = '/countries-profiles/jersey' WHERE name = 'Jersey';
UPDATE country SET profile_image_url = '/countries-profiles/jamaica' WHERE name = 'Jamaica';
UPDATE country SET profile_image_url = '/countries-profiles/japan' WHERE name = 'Japan';
UPDATE country SET profile_image_url = '/countries-profiles/jordan' WHERE name = 'Jordan';
UPDATE country SET profile_image_url = '/countries-profiles/kazakhstan' WHERE name = 'Kazakhstan';
UPDATE country SET profile_image_url = '/countries-profiles/kenya' WHERE name = 'Kenya';
UPDATE country SET profile_image_url = '/countries-profiles/kiribati' WHERE name = 'Kiribati';
UPDATE country SET profile_image_url = '/countries-profiles/north-korea' WHERE name = 'North Korea';
UPDATE country SET profile_image_url = '/countries-profiles/south-korea' WHERE name = 'South Korea';
UPDATE country SET profile_image_url = '/countries-profiles/kosovo' WHERE name = 'Kosovo';
UPDATE country SET profile_image_url = '/countries-profiles/kuwait' WHERE name = 'Kuwait';
UPDATE country SET profile_image_url = '/countries-profiles/kyrgyzstan' WHERE name = 'Kyrgyzstan';
UPDATE country SET profile_image_url = '/countries-profiles/lao-people''s-democratic-republic' WHERE name = 'Lao People''s Democratic Republic';
UPDATE country SET profile_image_url = '/countries-profiles/latvia' WHERE name = 'Latvia';
UPDATE country SET profile_image_url = '/countries-profiles/lebanon' WHERE name = 'Lebanon';
UPDATE country SET profile_image_url = '/countries-profiles/lesotho' WHERE name = 'Lesotho';
UPDATE country SET profile_image_url = '/countries-profiles/liberia' WHERE name = 'Liberia';
UPDATE country SET profile_image_url = '/countries-profiles/libyan-arab-jamahiriya' WHERE name = 'Libyan Arab Jamahiriya';
UPDATE country SET profile_image_url = '/countries-profiles/liechtenstein' WHERE name = 'Liechtenstein';
UPDATE country SET profile_image_url = '/countries-profiles/lithuania' WHERE name = 'Lithuania';
UPDATE country SET profile_image_url = '/countries-profiles/luxembourg' WHERE name = 'Luxembourg';
UPDATE country SET profile_image_url = '/countries-profiles/macau' WHERE name = 'Macau';
UPDATE country SET profile_image_url = '/countries-profiles/macedonia' WHERE name = 'Macedonia';
UPDATE country SET profile_image_url = '/countries-profiles/madagascar' WHERE name = 'Madagascar';
UPDATE country SET profile_image_url = '/countries-profiles/malawi' WHERE name = 'Malawi';
UPDATE country SET profile_image_url = '/countries-profiles/malaysia' WHERE name = 'Malaysia';
UPDATE country SET profile_image_url = '/countries-profiles/maldives' WHERE name = 'Maldives';
UPDATE country SET profile_image_url = '/countries-profiles/mali' WHERE name = 'Mali';
UPDATE country SET profile_image_url = '/countries-profiles/malta' WHERE name = 'Malta';
UPDATE country SET profile_image_url = '/countries-profiles/marshall-islands' WHERE name = 'Marshall Islands';
UPDATE country SET profile_image_url = '/countries-profiles/martinique' WHERE name = 'Martinique';
UPDATE country SET profile_image_url = '/countries-profiles/mauritania' WHERE name = 'Mauritania';
UPDATE country SET profile_image_url = '/countries-profiles/mauritius' WHERE name = 'Mauritius';
UPDATE country SET profile_image_url = '/countries-profiles/mayotte' WHERE name = 'Mayotte';
UPDATE country SET profile_image_url = '/countries-profiles/mexico' WHERE name = 'Mexico';
UPDATE country SET profile_image_url = '/countries-profiles/federated-states-of-micronesia' WHERE name = 'Micronesia, Federated States of';
UPDATE country SET profile_image_url = '/countries-profiles/republic-of-moldova' WHERE name = 'Moldova, Republic of';
UPDATE country SET profile_image_url = '/countries-profiles/monaco' WHERE name = 'Monaco';
UPDATE country SET profile_image_url = '/countries-profiles/mongolia' WHERE name = 'Mongolia';
UPDATE country SET profile_image_url = '/countries-profiles/montenegro' WHERE name = 'Montenegro';
UPDATE country SET profile_image_url = '/countries-profiles/montserrat' WHERE name = 'Montserrat';
UPDATE country SET profile_image_url = '/countries-profiles/morocco' WHERE name = 'Morocco';
UPDATE country SET profile_image_url = '/countries-profiles/mozambique' WHERE name = 'Mozambique';
UPDATE country SET profile_image_url = '/countries-profiles/myanmar' WHERE name = 'Myanmar';
UPDATE country SET profile_image_url = '/countries-profiles/namibia' WHERE name = 'Namibia';
UPDATE country SET profile_image_url = '/countries-profiles/nauru' WHERE name = 'Nauru';
UPDATE country SET profile_image_url = '/countries-profiles/nepal' WHERE name = 'Nepal';
UPDATE country SET profile_image_url = '/countries-profiles/netherlands' WHERE name = 'Netherlands';
UPDATE country SET profile_image_url = '/countries-profiles/netherlands-antilles' WHERE name = 'Netherlands Antilles';
UPDATE country SET profile_image_url = '/countries-profiles/new-caledonia' WHERE name = 'New Caledonia';
UPDATE country SET profile_image_url = '/countries-profiles/new-zealand' WHERE name = 'New Zealand';
UPDATE country SET profile_image_url = '/countries-profiles/nicaragua' WHERE name = 'Nicaragua';
UPDATE country SET profile_image_url = '/countries-profiles/niger' WHERE name = 'Niger';
UPDATE country SET profile_image_url = '/countries-profiles/nigeria' WHERE name = 'Nigeria';
UPDATE country SET profile_image_url = '/countries-profiles/niue' WHERE name = 'Niue';
UPDATE country SET profile_image_url = '/countries-profiles/norfolk-island' WHERE name = 'Norfolk Island';
UPDATE country SET profile_image_url = '/countries-profiles/northern-mariana-islands' WHERE name = 'Northern Mariana Islands';
UPDATE country SET profile_image_url = '/countries-profiles/norway' WHERE name = 'Norway';
UPDATE country SET profile_image_url = '/countries-profiles/oman' WHERE name = 'Oman';
UPDATE country SET profile_image_url = '/countries-profiles/pakistan' WHERE name = 'Pakistan';
UPDATE country SET profile_image_url = '/countries-profiles/palau' WHERE name = 'Palau';
UPDATE country SET profile_image_url = '/countries-profiles/palestine' WHERE name = 'Palestine';
UPDATE country SET profile_image_url = '/countries-profiles/panama' WHERE name = 'Panama';
UPDATE country SET profile_image_url = '/countries-profiles/papua-new-guinea' WHERE name = 'Papua New Guinea';
UPDATE country SET profile_image_url = '/countries-profiles/paraguay' WHERE name = 'Paraguay';
UPDATE country SET profile_image_url = '/countries-profiles/peru' WHERE name = 'Peru';
UPDATE country SET profile_image_url = '/countries-profiles/philippines' WHERE name = 'Philippines';
UPDATE country SET profile_image_url = '/countries-profiles/pitcairn' WHERE name = 'Pitcairn';
UPDATE country SET profile_image_url = '/countries-profiles/poland' WHERE name = 'Poland';
UPDATE country SET profile_image_url = '/countries-profiles/portugal' WHERE name = 'Portugal';
UPDATE country SET profile_image_url = '/countries-profiles/puerto-rico' WHERE name = 'Puerto Rico';
UPDATE country SET profile_image_url = '/countries-profiles/qatar' WHERE name = 'Qatar';
UPDATE country SET profile_image_url = '/countries-profiles/reunion' WHERE name = 'Reunion';
UPDATE country SET profile_image_url = '/countries-profiles/romania' WHERE name = 'Romania';
UPDATE country SET profile_image_url = '/countries-profiles/russian-federation' WHERE name = 'Russian Federation';
UPDATE country SET profile_image_url = '/countries-profiles/rwanda' WHERE name = 'Rwanda';
UPDATE country SET profile_image_url = '/countries-profiles/saint-kitts-and-nevis' WHERE name = 'Saint Kitts and Nevis';
UPDATE country SET profile_image_url = '/countries-profiles/saint-lucia' WHERE name = 'Saint Lucia';
UPDATE country SET profile_image_url = '/countries-profiles/saint-vincent-and-the-grenadines' WHERE name = 'Saint Vincent and the Grenadines';
UPDATE country SET profile_image_url = '/countries-profiles/samoa' WHERE name = 'Samoa';
UPDATE country SET profile_image_url = '/countries-profiles/san-marino' WHERE name = 'San Marino';
UPDATE country SET profile_image_url = '/countries-profiles/sao-tome-and-principe' WHERE name = 'Sao Tome and Principe';
UPDATE country SET profile_image_url = '/countries-profiles/saudi-arabia' WHERE name = 'Saudi Arabia';
UPDATE country SET profile_image_url = '/countries-profiles/senegal' WHERE name = 'Senegal';
UPDATE country SET profile_image_url = '/countries-profiles/serbia' WHERE name = 'Serbia';
UPDATE country SET profile_image_url = '/countries-profiles/seychelles' WHERE name = 'Seychelles';
UPDATE country SET profile_image_url = '/countries-profiles/sierra-leone' WHERE name = 'Sierra Leone';
UPDATE country SET profile_image_url = '/countries-profiles/singapore' WHERE name = 'Singapore';
UPDATE country SET profile_image_url = '/countries-profiles/slovakia' WHERE name = 'Slovakia';
UPDATE country SET profile_image_url = '/countries-profiles/slovenia' WHERE name = 'Slovenia';
UPDATE country SET profile_image_url = '/countries-profiles/solomon-islands' WHERE name = 'Solomon Islands';
UPDATE country SET profile_image_url = '/countries-profiles/somalia' WHERE name = 'Somalia';
UPDATE country SET profile_image_url = '/countries-profiles/south-africa' WHERE name = 'South Africa';
UPDATE country SET profile_image_url = '/countries-profiles/south-georgia-south-sandwich-islands' WHERE name = 'South Georgia South Sandwich Islands';
UPDATE country SET profile_image_url = '/countries-profiles/spain' WHERE name = 'Spain';
UPDATE country SET profile_image_url = '/countries-profiles/sri-lanka' WHERE name = 'Sri Lanka';
UPDATE country SET profile_image_url = '/countries-profiles/st.-helena' WHERE name = 'St. Helena';
UPDATE country SET profile_image_url = '/countries-profiles/st.-pierre-and-miquelon' WHERE name = 'St. Pierre and Miquelon';
UPDATE country SET profile_image_url = '/countries-profiles/sudan' WHERE name = 'Sudan';
UPDATE country SET profile_image_url = '/countries-profiles/suriname' WHERE name = 'Suriname';
UPDATE country SET profile_image_url = '/countries-profiles/svalbard-and-jan-mayen-islands' WHERE name = 'Svalbard and Jan Mayen Islands';
UPDATE country SET profile_image_url = '/countries-profiles/swaziland' WHERE name = 'Swaziland';
UPDATE country SET profile_image_url = '/countries-profiles/sweden' WHERE name = 'Sweden';
UPDATE country SET profile_image_url = '/countries-profiles/switzerland' WHERE name = 'Switzerland';
UPDATE country SET profile_image_url = '/countries-profiles/syrian-arab-republic' WHERE name = 'Syrian Arab Republic';
UPDATE country SET profile_image_url = '/countries-profiles/taiwan' WHERE name = 'Taiwan';
UPDATE country SET profile_image_url = '/countries-profiles/tajikistan' WHERE name = 'Tajikistan';
UPDATE country SET profile_image_url = '/countries-profiles/tanzania,-united-republic-of' WHERE name = 'Tanzania, United Republic of';
UPDATE country SET profile_image_url = '/countries-profiles/thailand' WHERE name = 'Thailand';
UPDATE country SET profile_image_url = '/countries-profiles/togo' WHERE name = 'Togo';
UPDATE country SET profile_image_url = '/countries-profiles/tokelau' WHERE name = 'Tokelau';
UPDATE country SET profile_image_url = '/countries-profiles/tonga' WHERE name = 'Tonga';
UPDATE country SET profile_image_url = '/countries-profiles/trinidad-and-tobago' WHERE name = 'Trinidad and Tobago';
UPDATE country SET profile_image_url = '/countries-profiles/tunisia' WHERE name = 'Tunisia';
UPDATE country SET profile_image_url = '/countries-profiles/turkey' WHERE name = 'Turkey';
UPDATE country SET profile_image_url = '/countries-profiles/turkmenistan' WHERE name = 'Turkmenistan';
UPDATE country SET profile_image_url = '/countries-profiles/turks-and-caicos-islands' WHERE name = 'Turks and Caicos Islands';
UPDATE country SET profile_image_url = '/countries-profiles/tuvalu' WHERE name = 'Tuvalu';
UPDATE country SET profile_image_url = '/countries-profiles/uganda' WHERE name = 'Uganda';
UPDATE country SET profile_image_url = '/countries-profiles/ukraine' WHERE name = 'Ukraine';
UPDATE country SET profile_image_url = '/countries-profiles/united-arab-emirates' WHERE name = 'United Arab Emirates';
UPDATE country SET profile_image_url = '/countries-profiles/united-kingdom' WHERE name = 'United Kingdom';
UPDATE country SET profile_image_url = '/countries-profiles/united-states' WHERE name = 'United States';
UPDATE country SET profile_image_url = '/countries-profiles/united-states-minor-outlying-islands' WHERE name = 'United States minor outlying islands';
UPDATE country SET profile_image_url = '/countries-profiles/uruguay' WHERE name = 'Uruguay';
UPDATE country SET profile_image_url = '/countries-profiles/uzbekistan' WHERE name = 'Uzbekistan';
UPDATE country SET profile_image_url = '/countries-profiles/vanuatu' WHERE name = 'Vanuatu';
UPDATE country SET profile_image_url = '/countries-profiles/vatican-city-state' WHERE name = 'Vatican City State';
UPDATE country SET profile_image_url = '/countries-profiles/venezuela' WHERE name = 'Venezuela';
UPDATE country SET profile_image_url = '/countries-profiles/vietnam' WHERE name = 'Vietnam';
UPDATE country SET profile_image_url = '/countries-profiles/british-virgin-islands' WHERE name = 'Virgin Islands (British)';
UPDATE country SET profile_image_url = '/countries-profiles/virgin-islands' WHERE name = 'Virgin Islands (U.S.)';
UPDATE country SET profile_image_url = '/countries-profiles/wallis-and-futuna-islands' WHERE name = 'Wallis and Futuna Islands';
UPDATE country SET profile_image_url = '/countries-profiles/western-sahara' WHERE name = 'Western Sahara';
UPDATE country SET profile_image_url = '/countries-profiles/yemen' WHERE name = 'Yemen';
UPDATE country SET profile_image_url = '/countries-profiles/zaire' WHERE name = 'Zaire';
UPDATE country SET profile_image_url = '/countries-profiles/zambia' WHERE name = 'Zambia';
UPDATE country SET profile_image_url = '/countries-profiles/zimbabwe' WHERE name = 'Zimbabwe';