INSERT INTO country VALUES (null, 'AF', 'Afghanistan', null, null);
INSERT INTO country VALUES (null, 'AL', 'Albania', null, null);
INSERT INTO country VALUES (null, 'DZ', 'Algeria', null, null);
INSERT INTO country VALUES (null, 'DS', 'American Samoa', null, null);
INSERT INTO country VALUES (null, 'AD', 'Andorra', null, null);
INSERT INTO country VALUES (null, 'AO', 'Angola', null, null);
INSERT INTO country VALUES (null, 'AI', 'Anguilla', null, null);
INSERT INTO country VALUES (null, 'AG', 'Antigua and Barbuda', null, null);
INSERT INTO country VALUES (null, 'AR', 'Argentina', null, null);
INSERT INTO country VALUES (null, 'AM', 'Armenia', null, null);
INSERT INTO country VALUES (null, 'AW', 'Aruba', null, null);
INSERT INTO country VALUES (null, 'AU', 'Australia', null, null);
INSERT INTO country VALUES (null, 'AT', 'Austria', null, null);
INSERT INTO country VALUES (null, 'AZ', 'Azerbaijan', null, null);
INSERT INTO country VALUES (null, 'BS', 'Bahamas', null, null);
INSERT INTO country VALUES (null, 'BH', 'Bahrain', null, null);
INSERT INTO country VALUES (null, 'BD', 'Bangladesh', null, null);
INSERT INTO country VALUES (null, 'BB', 'Barbados', null, null);
INSERT INTO country VALUES (null, 'BY', 'Belarus', null, null);
INSERT INTO country VALUES (null, 'BE', 'Belgium', null, null);
INSERT INTO country VALUES (null, 'BZ', 'Belize', null, null);
INSERT INTO country VALUES (null, 'BJ', 'Benin', null, null);
INSERT INTO country VALUES (null, 'BM', 'Bermuda', null, null);
INSERT INTO country VALUES (null, 'BT', 'Bhutan', null, null);
INSERT INTO country VALUES (null, 'BO', 'Bolivia', null, null);
INSERT INTO country VALUES (null, 'BA', 'Bosnia and Herzegovina', null, null);
INSERT INTO country VALUES (null, 'BW', 'Botswana', null, null);
INSERT INTO country VALUES (null, 'BR', 'Brazil', null, null);
INSERT INTO country VALUES (null, 'IO', 'British Indian Ocean Territory', null, null);
INSERT INTO country VALUES (null, 'BN', 'Brunei', null, null);
INSERT INTO country VALUES (null, 'BG', 'Bulgaria', null, null);
INSERT INTO country VALUES (null, 'BF', 'Burkina Faso', null, null);
INSERT INTO country VALUES (null, 'BI', 'Burundi', null, null);
INSERT INTO country VALUES (null, 'KH', 'Cambodia', null, null);
INSERT INTO country VALUES (null, 'CM', 'Cameroon', null, null);
INSERT INTO country VALUES (null, 'CA', 'Canada', null, null);
INSERT INTO country VALUES (null, 'CV', 'Cape Verde', null, null);
INSERT INTO country VALUES (null, 'KY', 'Cayman Islands', null, null);
INSERT INTO country VALUES (null, 'CF', 'Central African Republic', null, null);
INSERT INTO country VALUES (null, 'TD', 'Chad', null, null);
INSERT INTO country VALUES (null, 'CL', 'Chile', null, null);
INSERT INTO country VALUES (null, 'CN', 'China', null, null);
INSERT INTO country VALUES (null, 'CX', 'Christmas Island', null, null);
INSERT INTO country VALUES (null, 'CC', 'Cocos Island', null, null);
INSERT INTO country VALUES (null, 'CO', 'Colombia', null, null);
INSERT INTO country VALUES (null, 'KM', 'Comoros', null, null);
INSERT INTO country VALUES (null, 'CG', 'Democratic Republic of Congo', null, null);
INSERT INTO country VALUES (null, 'CG', 'Republic of The Congo', null, null);
INSERT INTO country VALUES (null, 'CK', 'Cook Islands', null, null);
INSERT INTO country VALUES (null, 'CR', 'Costa Rica', null, null);
INSERT INTO country VALUES (null, 'HR', 'Croatia', null, null);
INSERT INTO country VALUES (null, 'CU', 'Cuba', null, null);
INSERT INTO country VALUES (null, 'CY', 'Cyprus', null, null);
INSERT INTO country VALUES (null, 'CZ', 'Czech Republic', null, null);
INSERT INTO country VALUES (null, 'DK', 'Denmark', null, null);
INSERT INTO country VALUES (null, 'DJ', 'Djibouti', null, null);
INSERT INTO country VALUES (null, 'DM', 'Dominica', null, null);
INSERT INTO country VALUES (null, 'DO', 'Dominican Republic', null, null);
INSERT INTO country VALUES (null, 'TP', 'East Timor', null, null);
INSERT INTO country VALUES (null, 'EC', 'Ecuador', null, null);
INSERT INTO country VALUES (null, 'EG', 'Egypt', null, null);
INSERT INTO country VALUES (null, 'SV', 'Salvador', null, null);
INSERT INTO country VALUES (null, 'GQ', 'Equatorial Guinea', null, null);
INSERT INTO country VALUES (null, 'ER', 'Eritrea', null, null);
INSERT INTO country VALUES (null, 'EE', 'Estonia', null, null);
INSERT INTO country VALUES (null, 'ET', 'Ethiopia', null, null);
INSERT INTO country VALUES (null, 'FK', 'Falkland Islands', null, null);
INSERT INTO country VALUES (null, 'FO', 'Faroe Islands', null, null);
INSERT INTO country VALUES (null, 'FJ', 'Fiji', null, null);
INSERT INTO country VALUES (null, 'FI', 'Finland', null, null);
INSERT INTO country VALUES (null, 'FR', 'France', null, null);
INSERT INTO country VALUES (null, 'GF', 'Guyana', null, null);
INSERT INTO country VALUES (null, 'PF', 'French Polynesia', null, null);
INSERT INTO country VALUES (null, 'GA', 'Gabon', null, null);
INSERT INTO country VALUES (null, 'GM', 'Gambia', null, null);
INSERT INTO country VALUES (null, 'GE', 'Georgia', null, null);
INSERT INTO country VALUES (null, 'DE', 'Germany', null, null);
INSERT INTO country VALUES (null, 'GH', 'Ghana', null, null);
INSERT INTO country VALUES (null, 'GI', 'Gibraltar', null, null);
INSERT INTO country VALUES (null, 'GK', 'Guernsey', null, null);
INSERT INTO country VALUES (null, 'GR', 'Greece', null, null);
INSERT INTO country VALUES (null, 'GL', 'Greenland', null, null);
INSERT INTO country VALUES (null, 'GD', 'Grenada', null, null);
INSERT INTO country VALUES (null, 'GU', 'Guam', null, null);
INSERT INTO country VALUES (null, 'GT', 'Guatemala', null, null);
INSERT INTO country VALUES (null, 'GN', 'Guinea', null, null);
INSERT INTO country VALUES (null, 'GW', 'Guinea-Bissau', null, null);
INSERT INTO country VALUES (null, 'GY', 'Guyana', null, null);
INSERT INTO country VALUES (null, 'HT', 'Haiti', null, null);
INSERT INTO country VALUES (null, 'HN', 'Honduras', null, null);
INSERT INTO country VALUES (null, 'HK', 'Hong Kong', null, null);
INSERT INTO country VALUES (null, 'HU', 'Hungary', null, null);
INSERT INTO country VALUES (null, 'IS', 'Iceland', null, null);
INSERT INTO country VALUES (null, 'IN', 'India', null, null);
INSERT INTO country VALUES (null, 'IM', 'Isle of Man', null, null);
INSERT INTO country VALUES (null, 'ID', 'Indonesia', null, null);
INSERT INTO country VALUES (null, 'IR', 'Iran', null, null);
INSERT INTO country VALUES (null, 'IQ', 'Iraq', null, null);
INSERT INTO country VALUES (null, 'IE', 'Ireland', null, null);
INSERT INTO country VALUES (null, 'IL', 'Israel', null, null);
INSERT INTO country VALUES (null, 'IT', 'Italy', null, null);
INSERT INTO country VALUES (null, 'CI', 'Ivory Coast', null, null);
INSERT INTO country VALUES (null, 'JE', 'Jersey', null, null);
INSERT INTO country VALUES (null, 'JM', 'Jamaica', null, null);
INSERT INTO country VALUES (null, 'JP', 'Japan', null, null);
INSERT INTO country VALUES (null, 'JO', 'Jordan', null, null);
INSERT INTO country VALUES (null, 'KZ', 'Kazakhstan', null, null);
INSERT INTO country VALUES (null, 'KE', 'Kenya', null, null);
INSERT INTO country VALUES (null, 'KI', 'Kiribati', null, null);
INSERT INTO country VALUES (null, 'KP', 'North Korea', null, null);
INSERT INTO country VALUES (null, 'KR', 'South Korea', null, null);
INSERT INTO country VALUES (null, 'XK', 'Kosovo', null, null);
INSERT INTO country VALUES (null, 'KW', 'Kuwait', null, null);
INSERT INTO country VALUES (null, 'KG', 'Kyrgyzstan', null, null);
INSERT INTO country VALUES (null, 'LA', 'Lao People''s Democratic Republic', null, null);
INSERT INTO country VALUES (null, 'LV', 'Latvia', null, null);
INSERT INTO country VALUES (null, 'LB', 'Lebanon', null, null);
INSERT INTO country VALUES (null, 'LS', 'Lesotho', null, null);
INSERT INTO country VALUES (null, 'LR', 'Liberia', null, null);
INSERT INTO country VALUES (null, 'LY', 'Libyan Arab Jamahiriya', null, null);
INSERT INTO country VALUES (null, 'LI', 'Liechtenstein', null, null);
INSERT INTO country VALUES (null, 'LT', 'Lithuania', null, null);
INSERT INTO country VALUES (null, 'LU', 'Luxembourg', null, null);
INSERT INTO country VALUES (null, 'MO', 'Macau', null, null);
INSERT INTO country VALUES (null, 'MK', 'Macedonia', null, null);
INSERT INTO country VALUES (null, 'MG', 'Madagascar', null, null);
INSERT INTO country VALUES (null, 'MW', 'Malawi', null, null);
INSERT INTO country VALUES (null, 'MY', 'Malaysia', null, null);
INSERT INTO country VALUES (null, 'MV', 'Maldives', null, null);
INSERT INTO country VALUES (null, 'ML', 'Mali', null, null);
INSERT INTO country VALUES (null, 'MT', 'Malta', null, null);
INSERT INTO country VALUES (null, 'MH', 'Marshall Islands', null, null);
INSERT INTO country VALUES (null, 'MQ', 'Martinique', null, null);
INSERT INTO country VALUES (null, 'MR', 'Mauritania', null, null);
INSERT INTO country VALUES (null, 'MU', 'Mauritius', null, null);
INSERT INTO country VALUES (null, 'TY', 'Mayotte', null, null);
INSERT INTO country VALUES (null, 'MX', 'Mexico', null, null);
INSERT INTO country VALUES (null, 'FM', 'Micronesia, Federated States of', null, null);
INSERT INTO country VALUES (null, 'MD', 'Moldova, Republic of', null, null);
INSERT INTO country VALUES (null, 'MC', 'Monaco', null, null);
INSERT INTO country VALUES (null, 'MN', 'Mongolia', null, null);
INSERT INTO country VALUES (null, 'ME', 'Montenegro', null, null);
INSERT INTO country VALUES (null, 'MS', 'Montserrat', null, null);
INSERT INTO country VALUES (null, 'MA', 'Morocco', null, null);
INSERT INTO country VALUES (null, 'MZ', 'Mozambique', null, null);
INSERT INTO country VALUES (null, 'MM', 'Myanmar', null, null);
INSERT INTO country VALUES (null, 'NA', 'Namibia', null, null);
INSERT INTO country VALUES (null, 'NR', 'Nauru', null, null);
INSERT INTO country VALUES (null, 'NP', 'Nepal', null, null);
INSERT INTO country VALUES (null, 'NL', 'Netherlands', null, null);
INSERT INTO country VALUES (null, 'AN', 'Netherlands Antilles', null, null);
INSERT INTO country VALUES (null, 'NC', 'New Caledonia', null, null);
INSERT INTO country VALUES (null, 'NZ', 'New Zealand', null, null);
INSERT INTO country VALUES (null, 'NI', 'Nicaragua', null, null);
INSERT INTO country VALUES (null, 'NE', 'Niger', null, null);
INSERT INTO country VALUES (null, 'NG', 'Nigeria', null, null);
INSERT INTO country VALUES (null, 'NU', 'Niue', null, null);
INSERT INTO country VALUES (null, 'NF', 'Norfolk Island', null, null);
INSERT INTO country VALUES (null, 'MP', 'Northern Mariana Islands', null, null);
INSERT INTO country VALUES (null, 'NO', 'Norway', null, null);
INSERT INTO country VALUES (null, 'OM', 'Oman', null, null);
INSERT INTO country VALUES (null, 'PK', 'Pakistan', null, null);
INSERT INTO country VALUES (null, 'PW', 'Palau', null, null);
INSERT INTO country VALUES (null, 'PS', 'Palestine', null, null);
INSERT INTO country VALUES (null, 'PA', 'Panama', null, null);
INSERT INTO country VALUES (null, 'PG', 'Papua New Guinea', null, null);
INSERT INTO country VALUES (null, 'PY', 'Paraguay', null, null);
INSERT INTO country VALUES (null, 'PE', 'Peru', null, null);
INSERT INTO country VALUES (null, 'PH', 'Philippines', null, null);
INSERT INTO country VALUES (null, 'PN', 'Pitcairn', null, null);
INSERT INTO country VALUES (null, 'PL', 'Poland', null, null);
INSERT INTO country VALUES (null, 'PT', 'Portugal', null, null);
INSERT INTO country VALUES (null, 'PR', 'Puerto Rico', null, null);
INSERT INTO country VALUES (null, 'QA', 'Qatar', null, null);
INSERT INTO country VALUES (null, 'RE', 'Reunion', null, null);
INSERT INTO country VALUES (null, 'RO', 'Romania', null, null);
INSERT INTO country VALUES (null, 'RU', 'Russian Federation', null, null);
INSERT INTO country VALUES (null, 'RW', 'Rwanda', null, null);
INSERT INTO country VALUES (null, 'KN', 'Saint Kitts and Nevis', null, null);
INSERT INTO country VALUES (null, 'LC', 'Saint Lucia', null, null);
INSERT INTO country VALUES (null, 'VC', 'Saint Vincent and the Grenadines', null, null);
INSERT INTO country VALUES (null, 'WS', 'Samoa', null, null);
INSERT INTO country VALUES (null, 'SM', 'San Marino', null, null);
INSERT INTO country VALUES (null, 'ST', 'Sao Tome and Principe', null, null);
INSERT INTO country VALUES (null, 'SA', 'Saudi Arabia', null, null);
INSERT INTO country VALUES (null, 'SN', 'Senegal', null, null);
INSERT INTO country VALUES (null, 'RS', 'Serbia', null, null);
INSERT INTO country VALUES (null, 'SC', 'Seychelles', null, null);
INSERT INTO country VALUES (null, 'SL', 'Sierra Leone', null, null);
INSERT INTO country VALUES (null, 'SG', 'Singapore', null, null);
INSERT INTO country VALUES (null, 'SK', 'Slovakia', null, null);
INSERT INTO country VALUES (null, 'SI', 'Slovenia', null, null);
INSERT INTO country VALUES (null, 'SB', 'Solomon Islands', null, null);
INSERT INTO country VALUES (null, 'SO', 'Somalia', null, null);
INSERT INTO country VALUES (null, 'ZA', 'South Africa', null, null);
INSERT INTO country VALUES (null, 'GS', 'South Georgia South Sandwich Islands', null, null);
INSERT INTO country VALUES (null, 'ES', 'Spain', null, null);
INSERT INTO country VALUES (null, 'LK', 'Sri Lanka', null, null);
INSERT INTO country VALUES (null, 'SH', 'St. Helena', null, null);
INSERT INTO country VALUES (null, 'PM', 'St. Pierre and Miquelon', null, null);
INSERT INTO country VALUES (null, 'SD', 'Sudan', null, null);
INSERT INTO country VALUES (null, 'SR', 'Suriname', null, null);
INSERT INTO country VALUES (null, 'SJ', 'Svalbard and Jan Mayen Islands', null, null);
INSERT INTO country VALUES (null, 'SZ', 'Swaziland', null, null);
INSERT INTO country VALUES (null, 'SE', 'Sweden', null, null);
INSERT INTO country VALUES (null, 'CH', 'Switzerland', null, null);
INSERT INTO country VALUES (null, 'SY', 'Syrian Arab Republic', null, null);
INSERT INTO country VALUES (null, 'TW', 'Taiwan', null, null);
INSERT INTO country VALUES (null, 'TJ', 'Tajikistan', null, null);
INSERT INTO country VALUES (null, 'TZ', 'Tanzania, United Republic of', null, null);
INSERT INTO country VALUES (null, 'TH', 'Thailand', null, null);
INSERT INTO country VALUES (null, 'TG', 'Togo', null, null);
INSERT INTO country VALUES (null, 'TK', 'Tokelau', null, null);
INSERT INTO country VALUES (null, 'TO', 'Tonga', null, null);
INSERT INTO country VALUES (null, 'TT', 'Trinidad and Tobago', null, null);
INSERT INTO country VALUES (null, 'TN', 'Tunisia', null, null);
INSERT INTO country VALUES (null, 'TR', 'Turkey', null, null);
INSERT INTO country VALUES (null, 'TM', 'Turkmenistan', null, null);
INSERT INTO country VALUES (null, 'TC', 'Turks and Caicos Islands', null, null);
INSERT INTO country VALUES (null, 'TV', 'Tuvalu', null, null);
INSERT INTO country VALUES (null, 'UG', 'Uganda', null, null);
INSERT INTO country VALUES (null, 'UA', 'Ukraine', null, null);
INSERT INTO country VALUES (null, 'AE', 'United Arab Emirates', null, null);
INSERT INTO country VALUES (null, 'GB', 'United Kingdom', null, null);
INSERT INTO country VALUES (null, 'US', 'United States', null, null);
INSERT INTO country VALUES (null, 'UM', 'United States minor outlying islands', null, null);
INSERT INTO country VALUES (null, 'UY', 'Uruguay', null, null);
INSERT INTO country VALUES (null, 'UZ', 'Uzbekistan', null, null);
INSERT INTO country VALUES (null, 'VU', 'Vanuatu', null, null);
INSERT INTO country VALUES (null, 'VA', 'Vatican City State', null, null);
INSERT INTO country VALUES (null, 'VE', 'Venezuela', null, null);
INSERT INTO country VALUES (null, 'VN', 'Vietnam', null, null);
INSERT INTO country VALUES (null, 'VG', 'Virgin Islands (British)', null, null);
INSERT INTO country VALUES (null, 'VI', 'Virgin Islands (U.S.)', null, null);
INSERT INTO country VALUES (null, 'WF', 'Wallis and Futuna Islands', null, null);
INSERT INTO country VALUES (null, 'EH', 'Western Sahara', null, null);
INSERT INTO country VALUES (null, 'YE', 'Yemen', null, null);
INSERT INTO country VALUES (null, 'ZR', 'Zaire', null, null);
INSERT INTO country VALUES (null, 'ZM', 'Zambia', null, null);
INSERT INTO country VALUES (null, 'ZW', 'Zimbabwe', null, null);
